### ISSUE TITLE
Cannot add custom component as a new widget

### ISSUE THREAD

**Issue by Vixys** [hamzahamidi/Angular6-json-schema-form#113]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
Cannot add custom component as a new widget.

**To Reproduce**

1. Create component
2. Register it through the `[widget]` input

**Expected behavior**
The component of the custom widget is loaded.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version 73

**Additional context**
I am trying to add a custom widget. But the output schema differ from the input schema.
The `type` field is deleted from the object during the call of `convertSchemaToDraft6` beacause it is not part of the `simpleTypes` array, which is normal as it is a new custom widget.

The documentation does not specify if there anything to do to be able to use custom widgets.

**Comment by Vixys** [comment]
After taking a closer look at the documentation I understood that I have to set the custom widget in `layout `not in `schema`

Therefore I close this issue.

**Comment by MateMahinKhan** [comment]
@Vixys where did you see that custom widget should be in `layout`?

**Comment by jvall** [comment]
@MateMahinKhan @Vixys I've got the same problem over in #249, did you know what ended up working here? I couldn't find in the documentation that it should be in `layout` either.

**Comment by MateMahinKhan** [comment]
@jvall This is a really good project, I don't remember finding a solution to this but I ended up using [Formly](https://github.com/ngx-formly/ngx-formly). I know this doesn't answer your question but could give you more chance to explore.
