### ISSUE TITLE
 Must be a date, like 2000-12-31

### ISSUE THREAD

**Issue by alijohn** [hamzahamidi/Angular6-json-schema-form#124]
Hello,
Thanks for all the updates. Recent change have caused a validation error for date formatted property.

"birthday": { "type": "string", "format": "date" },

Error Must be a date, like 2000-12-31

Is there a work around to keep the format as 'date' and not cause an error

**Comment by hamzahamidi** [comment]
Thanks @alijohn . The issue is reproducible in Material

**Comment by hamzahamidi** [comment]
Linked to https://github.com/hamzahamidi/Angular6-json-schema-form/commit/95772069f0981b37486c697c3ba9d3123bf64bb8
