### ISSUE TITLE
Object enum with uid for each element

### ISSUE THREAD

**Issue by agjs** [hamzahamidi/Angular6-json-schema-form#136]
Hey guys, is it possible to have a schema where we have an enum of objects?

```
<select>
  <option data-uid="someUniqueId">SomeText</option>
</select>
```

Right now I have a list of some things that I want to show but enum of strings is not sufficient because each one of those objects has an ID that I essentially need to grab when user selects an option in a select input like shown above.

So, is it possible to have something like:

```
{
"type": "object"
"enum": [{"name": "SomeText", uid: "someUniqueId"}]
}
```

Thanks in advance

**Comment by jackcw** [comment]
For those that comes across this issue the solution is 
```
{
    "status": {
        "title": "Status",
        "type": "string",
        "enum": [
            "active",
            "draft",
            "archived"
        ],
        "enumNames": {
            "active": "Active",
            "draft": "Draft",
            "archived": "Archived"
        }
    }
}
```
