### ISSUE TITLE
Override default "object" widget

### ISSUE THREAD

**Issue by jakubjosef** [hamzahamidi/Angular6-json-schema-form#14]
Hi, 
in our application we don't want to use embedded object nesting features of this framework.
Instead of this we want to display link which will be used as a entrypoint for generating new form.

So we have custom widget called object-link, I can easily use them for objects using custom layout but I also want to use default nesting features for arrays and things like that.

Right now i have to generate layout dynamically, replace all occurences of `type:object` with `type:object-link` and dynamically reconstruct the layout for other types (arrays and things like this).

I have complicated recursive function to do that and it works relatively good but best solution is to specify no layout to use embedded features and just replace objects.

Creating complete custom layout for features this plugin already have is pain... Unfortunately using our `object-link` widget as a override of "object" or "fieldset" types no work.

Do you have any ideas how to do that, thank you in advance very much.

**Comment by hamzahamidi** [comment]
Thank you @jakubjosef  for the issue. Can you point me the widget you're trying to override?

**Comment by jakubjosef** [comment]
Looks like I described it in bad way. We dont need to override any "widget" we need to override behaviour for dealing with `type: object` properties, is it better understandable right now?

**Comment by jakubjosef** [comment]
In other words we just need to override default behaviour for `type:object`, but OK it looks like it's not possible. Unfortunately it seems we have to implement complete solution without any plugin to cover our company needs. Anyway thank you for your help regarding issues in this project.
