### ISSUE TITLE
Click input will cause title shake

### ISSUE THREAD

**Issue by a2928897** [hamzahamidi/Angular6-json-schema-form#141]
**Describe the bug**
which template:

* [ V] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

form look is fine, but when i click a input,
all title will be shake,
just on chrome, edge or firefox will be fine
only occur on material design, other framework will be fine

**To Reproduce**

1.i use schematics ng generate @angular/material:nav <component-name>
2.add a conponent &import angular6-json
3.test example like below
4.click any input, all title like address and phone_numbers will be shake, it's weird

example code
`<json-schema-form
  loadExternalAssets="true"
 framework="material-design"
  [(ngModel)]="exampleJsonObject">
</json-schema-form>`

`exampleJsonObject = {
  "first_name": "Jane", "last_name": "Doe", "age": 25, "is_company": false,
  "address": {
    "street_1": "123 Main St.", "street_2": null,
    "city": "Las Vegas", "state": "NV", "zip_code": "89123"
  },
  "phone_numbers": [
    { "number": "702-123-4567", "type": "cell" },
    { "number": "702-987-6543", "type": "work" }
  ], "notes": ""
};`

when i click input, title don't be shaked

**Screenshots**
![title shake](https://user-images.githubusercontent.com/13020589/63480172-7c06d480-c4c3-11e9-83d9-c9c00eb27074.gif)

- Browser [chrome]
- Version [75.0.3770.142]

**Additional context**

**Comment by a2928897** [comment]
![ScreenGif](https://user-images.githubusercontent.com/13020589/63504663-990fc780-c504-11e9-8ee9-314cc9f85ac0.gif)
Watch address and phone numbers

**Comment by a2928897** [comment]
Ok i already know why this happend

I found, When I click my input,
browser will send a request for css Roboto like above
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">

The URL like Robot:300,400,500 and 700, that's different from my URL,
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">

So my css be changed when i click input.


I feel weired,then I found
\node_modules\angular6-json-schema-form\fesm2015\angular6-json-schema-form.js
In this js, 
`<div *ngFor="let stylesheet of stylesheets">
<link rel="stylesheet" [href]="stylesheet">
</div>`
Will get what i ref in my index.html,every time i click my input, will cause this happend 
When I delete this code,
Everything is fine,

Thanks a lot, sorry about my poor english.

**Comment by gornad** [comment]
I was having the same problem. To fix it, I removed loadExternalAssets="true" from the json-schema-form definition. No need to change the library itself. As explained in documentation: These are the external stylesheets and scripts that will be loaded if the "loadExternalAssets" option is set to "true".
