### ISSUE TITLE
WidgetLibraryService can not be imported correctly

### ISSUE THREAD

**Issue by sasos90** [hamzahamidi/Angular6-json-schema-form#16]
Hi!

I am trying to port form angular2-json-schema-form to angular6-json-schema-form but I am having some issues with it.
I am using WidgetLibraryService like this:

... importing the service at the top of the file:
import { WidgetLibraryService } from 'angular6-json-schema-form/lib/widget-library/widget-library.service';
**(also tried with:)**
import { WidgetLibraryService } from 'angular6-json-schema-form';

... injecting the provider in constructor:
private widgetLibrary: WidgetLibraryService

... registering widgets:
widgetLibrary.registerWidget('widgetone', WidgetOneComponent);
widgetLibrary.registerWidget('text', InputComponent);
widgetLibrary.registerWidget('textarea', TextareaComponent);

But when I try to serve the app (non-prod), I get the following error:
ERROR in src/app/layout/content/content-create/content-create.component.ts(43,10): error TS2305: Module '"xxx/xxx/xxx/xxx/myproject/node_modules/angular6-json-schema-form/angular6-json-schema-form"' has no exported member 'WidgetLibraryService'.

What could be the problem here?

which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. Use the code snippet from above.
2. Run "npm run start" for serving the app (ng serve)

**Expected behavior**
To have no errors at serving the app.

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [latest]

**Comment by blained3** [comment]
I use this service regularly to create different widgets. If you know a potential fix for it I would be willing to submit a merge request. I just need this ASAP. Thanks!

**Comment by hamzahamidi** [comment]
Closing as it was already fixed in https://github.com/hamzahamidi/Angular6-json-schema-form/pull/10/files#diff-55
