### ISSUE TITLE
Future compatibility with Angular v8?

### ISSUE THREAD

**Issue by jormaje** [hamzahamidi/Angular6-json-schema-form#160]
**Describe the bug**
`Package "codelyzer" has an incompatible peer dependency to "@angular/common" (requires ">=2.3.1 <7.0.0 || >6.0.0-beta <7.0.0" (extended), would install "8.2.12")`
...

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
I am struggling with incompatibilities  on updating this demo https://stackblitz.com/edit/angular6-json-schema-form to Angular v8.

**To Reproduce**
1. Clone and run this demo https://stackblitz.com/edit/angular6-json-schema-form on Angular v7
2. Update Angular (@angular/core, @angular/cli, @angular/compiler-cli, etc.) to last version (v8)
3. ng serve

**Expected behavior**
Compiled succesfully.

**Comment by hamzahamidi** [comment]
The demo in Stackblitz is working fine. If you're using Angularv8 you need to use the version ^8.0.0 of this library.
