### ISSUE TITLE
Layouting: Put e.g. 2 fieldsets / sections next to each other?

### ISSUE THREAD

**Issue by stretau** [hamzahamidi/Angular6-json-schema-form#18]
which template:
* [X] Bootstrap4FrameworkModule — Bootstrap 4
  
**Question / To Reproduce**
Is it possible (if not could you enhance) to make e.g. 2 fieldsets or sections next to each other?

Consider the following schema:

```
{
            "schema" : {
              "properties": {
                "inv_code": {
                  "description": "Invoice number",
                  "type": "string"
                },
                "inv_amount": {
                  "description": "Anount",
                  "type": "number",
                }
              },
              "required": [
                "inv_code",
                "inv_amount"
              ]
            },
            "form" : [
              {
                "type" : "section",
                "items" : [
                  {
                    "type": "fieldset",
                    "title" : "Code",
                    "htmlClass" : "col-6",
                    "items": [ "inv_code" ]
                  },
                  {
                    "type" : "fieldset",
                    "title" : "Amount",
                    "htmlClass" : "col-6",
                    "items": ["inv_amount"]
                  }
                ]
              }
            ]
        }
```
This renders the following:

![schema-form-test](https://user-images.githubusercontent.com/23280769/45145759-b481a580-b1c1-11e8-8258-ece039b63c92.png)

As you can see ... each of the 2 fieldsets have the col-6 width (from bootstrap), but both are not shown next to each other. This I would expect in this case, would I?

Of course I know of the opportunity to put two fields next to each other like in the flex-layout example [https://hamidihamza.com/Angular6-json-schema-form/?set=ng-jsf&example=ng-jsf-flex-layout&framework=bootstrap-4&language=en](url)

But in my opinion the problem described above is a different case.

Thx in advance, best regards

**Comment by stalsma-palmetto** [comment]
You should be able to apply class to section...

```
{
      "htmlClass": "row",
      "type": "section",
```
