### ISSUE TITLE
error while running yarn commands

### ISSUE THREAD

**Issue by santoshbilla** [hamzahamidi/Angular6-json-schema-form#26]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [x] Other (please specify below)
  

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by santoshbilla** [comment]
ERROR in ./src/app/demo.module.ts
Module not found: Error: Can't resolve '/Users/store/Downloads/angular-schema-form/angular6-json-schema-form/dist/angular6-json-schema-form' in '/Users/store/Downloads/angular-schema-form/angular6-json-schema-form/src/app'
ERROR in ./src/app/demo.component.ts
Module not found: Error: Can't resolve '/Users/store/Downloads/angular-schema-form/angular6-json-schema-form/dist/angular6-json-schema-form' in '/Users/store/Downloads/angular-schema-form/angular6-json-schema-form/src/app'
ℹ ｢wdm｣: Failed to compile.

**Comment by santoshbilla** [comment]
this is after running the yarn commands as mentioned here: 
https://www.npmjs.com/package/angular6-json-schema-form

**Comment by hamzahamidi** [comment]
You need to run the following commands:
- git clone https://github.com/hamzahamidi/angular6-json-schema-form.git angular6-json-schema-form
- cd angular6-json-schema-form
- yarn install
- yarn buildlib
- yarn start

**Comment by santoshbilla** [comment]
Thanks @hamzahamidi it works now
