### ISSUE TITLE
Is there a way to add alt, placeholder to the Label tag?  Also is there a way to add angular directive to the elements?

### ISSUE THREAD

**Issue by santoshbilla** [hamzahamidi/Angular6-json-schema-form#28]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
Insert log hereCopy
```

**Additional context**

**Detailed Description**

**Context**

**Possible Implementation**

**Comment by hamzahamidi** [comment]
You can add the key placeholder & give it a value in the json schema. As for the other options the library doesn't support it.
