### ISSUE TITLE
Create Angular7-json-schema-form

### ISSUE THREAD

**Issue by adampenn** [hamzahamidi/Angular6-json-schema-form#32]
Hello,

I was in need of a few fixes to this repo that I didn't have time to get a PR approved for so I forked it and while I was fixing those I also upgraded to angular 7. You can check it out [here](https://github.com/adampenn/Angular7-json-schema-form).

**Comment by adampenn** [comment]
@hamzahamidi I am also happy to add you as a collaborator since you seem to be the main contributor to this project.

**Comment by hamzahamidi** [comment]
Thanks @adampenn for your help. the PR for Angular v7 is now merged.
