### ISSUE TITLE
Date selected using a Datepicker causes selected date to 1 day backward.

### ISSUE THREAD

**Issue by sai7** [hamzahamidi/Angular6-json-schema-form#35]
**Describe the bug**
which template:

* [√ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. Setup the library in an Angular v6 app as specified in the docs.
2. Used material design framework.
3. Defined schema and layout for the form.
4. The date type form field, which on selecting a date will go 1 day backward. For e.g., if I select 9Nov2018, it will be set in the form as 8Nov2018.

**Expected behavior**
On selecting a date from the date picker, it should set a correct selected date in the form.

**Desktop (please complete the following information):**

- OS: [MacOS, Windows]
- Browser [ chrome, safari]
- Version [12, 70.0.3538.77]

**Additional context**
Please let me know how to handle this scenario. We are planning to deploy this app in the production where clients will be using this forms.

**Context**

This change is really important because we have an application that requires a lot of date fields and the dates are being set 1 day backward by using this form.

I am not sure why others are not getting this behavior or have they handled this by themselves?

**Comment by Benjitos** [comment]
https://github.com/hamzahamidi/Angular6-json-schema-form/pull/39/commits/5c180bd6e37fde425726ebbe4289d30e64073ab5

**Comment by hamzahamidi** [comment]
I will check this out. I'm truely very busy these days, so I dont have much time to work on the library.

**Comment by sai7** [comment]
> 5c180bd

Thanks, @Benjitos, @hamzahamidi. This commit doesn't resolve the date issue in different time zones. For my local system, it's working fine. After deploying the app in EC2 instance, the date behaves as shown in the following video. Please check it here: [https://youtu.be/D0iwFov4t7Q](https://youtu.be/D0iwFov4t7Q)

**Scenario:** 
Let's say if I select a date as **14th**, the displayed date will be **12th**, but the date in the model will be **13th**

Initially, after your last commit, I updated my package to v7.0.1, this issue seems to be solved in my local date settings. But after deploying in the client environment, I still got this issue intact.

**Comment by hamzahamidi** [comment]
#71
