### ISSUE TITLE
JsonPointer related issue..

### ISSUE THREAD

**Issue by RS-Roshi** [hamzahamidi/Angular6-json-schema-form#44]
Can't resolve an external local file reference in $ref. 
Is there any solution to use local external schema file reference in $ref.

**Comment by RS-Roshi** [comment]
This is my main schema file...
```
{
   
    "type": "object",
  
    "properties": {
      "billing_address": { "$ref": "definitions.json#/address" }
    }
  }
```
and this is definitions.json ... both files are in src/assets/shemas
```
{
  "id": "definitions",
  "address": {
    "type": "object",
    "properties": {
      "street_address": { "type": "string" },
      "city":           { "type": "string" },
      "state":          { "type": "string" }
    },
    "required": ["street_address", "city", "state"]
  }
}
```
i have tired different paths in "$ref" and also removed "id": "definitions" but this is not helping the same schema generates form if i write definitions and properties both in one json file. but like this its giving following error

> ERROR 
Object { message: "can't resolve reference definitions.json#/address from id #", missingRef: "definitions.json#/address", missingSchema: "definitions.json", ngDebugContext: {…}, ngErrorLogger: (), stack: "" }

**Comment by hamzahamidi** [comment]
You need to remove $ from $ref

**Comment by RS-Roshi** [comment]
> 
> 
> You need to remove $ from $ref

ref is not even referring inside the same json file If i remove $ref and make it ref it will not work. its not a JSON schema keyword.

**Comment by saulgill** [comment]
@RS-Roshi and @hamzahamidi. Was there ever a resolution found for this? Can we just not use "$ref" at all?

**Comment by hamzahamidi** [comment]
#72
