### ISSUE TITLE
Can`t use it without schema 2

### ISSUE THREAD

**Issue by pharindoko** [hamzahamidi/Angular6-json-schema-form#53]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

Use plain json without schema
It fails to validate - schema is undefined

More details:

ajv.js
```
function validate(schemaKeyRef, data) {
	...
    v = this.getSchema(schemaKeyRef);
	...
}
```

ajv.js line 238
It compares keyRef = "http://json-schema.org/draft-06/schema# with "http://json-schema.org/draft-07/schema"

```
  return self._schemas[keyRef] || self._refs[keyRef] || self._fragments[keyRef];
```
 
 result "undefined" will be returned
 
**Error in line 92 will be thrown:**
```
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
```

**Expected behavior**

The correct schema will be taken

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Angular 7

**Comment by hamzahamidi** [comment]
Noted I'll check this out asap

**Comment by hamzahamidi** [comment]
Duplicate #52
