### ISSUE TITLE
When using "no-framework" and no desire for angular material, app tries to compile angular material.

### ISSUE THREAD

**Issue by mrmillross** [hamzahamidi/Angular6-json-schema-form#65]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

**To Reproduce**

1. ...

**Expected behavior**
Use no-framework and plain html with a pre-defined schema

**Screenshots**

**Desktop (please complete the following information):**

**Log output covering before error and any error statements**

```logs
ERROR in angular6-json-schema-form\angular6-json-schema-form.ts(51,53): Error during template compile of 'MaterialDesignFrameworkModule'
  Could not resolve @angular/flex-layout relative to C:/dev/FunPassport/src/FunFair.FunPassport.Web/node_modules/angular6-json-schema-form/angular6-json-schema-form.d.ts..
node_modules/angular6-json-schema-form/lib/framework-library/material-design-framework/material-design-framework.module.d.ts(1,37): error TS2307: Cannot find module '@angular/material'.
```

**Additional context**
Using typescript components and angular cli based project, version 6+

**Detailed Description**

**Context**

**Possible Implementation**

How can I make this work without templates?

**Comment by ratkorle** [comment]
Same here, even if I choose Bootstrap4FrameworkModule I got the same error.

I also want to ask is there a possibility that at some point user can name object keys?

**Comment by hamzahamidi** [comment]
Duplicate #17
