### ISSUE TITLE
Bug in flex layout with nested objects

### ISSUE THREAD

**Issue by woutervs** [hamzahamidi/Angular6-json-schema-form#73]
**Describe the bug**
which template:

MaterialDesignFrameworkModule — Material Design
  

![image](https://user-images.githubusercontent.com/5603059/51122754-d26bb080-181a-11e9-8214-f967466a080b.png)

**To Reproduce**
    schema: {
      type: "object",
      title: "Comment",
      properties: {
        name: {
          title: "Name",
          type: "string"
        },
        email: {
          title: "Email",
          type: "string",
          pattern: "^\\S+@\\S+$",
          description: "Email will be used for evil."
        },
        comment: {
          title: "Comment",
          type: "string",
          maxLength: 20,
          validationMessage: "Don't be greedy!"
        },
        contact: {
          type: "object",
          title: "Contact",
          properties: {
            firstname: {
              title: "Firstname",
              type: "string"
            },
            lastname: {
              title: "Lastname",
              type: "string"
            }
          }
        }
      },
      required: [
        "name",
        "email",
        "comment"
      ]
    }

**Expected behavior**
No error should occur here

**Desktop (please complete the following information):**

- OS: Win10
- Browser Chrome/Edge
- Version Latest on both

**Log output covering before error and any error statements**

```logs
Uncaught TypeError: Cannot read property 'endsWith' of undefined
    at LayoutGapStyleBuilder.push../node_modules/@angular/flex-layout/esm5/flex.es5.js.LayoutGapStyleBuilder.buildStyles (vendor.js:89982)
    at DefaultLayoutGapDirective.push../node_modules/@angular/flex-layout/esm5/core.es5.js.BaseDirective2.addStyles (vendor.js:85516)
    at DefaultLayoutGapDirective.push../node_modules/@angular/flex-layout/esm5/flex.es5.js.LayoutGapDirective.updateWithValue (vendor.js:90190)
    at MediaMarshaller.push../node_modules/@angular/flex-layout/esm5/core.es5.js.MediaMarshaller.updateElement (vendor.js:88331)
    at SafeSubscriber._next (vendor.js:88421)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (vendor.js:188363)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (vendor.js:188301)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (vendor.js:188244)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (vendor.js:188221)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext (vendor.js:193797)
```

**Additional context**
Problem only happens with nested objects seems so far

**Comment by woutervs** [comment]
I'm going to link this issue in the pull request with a fix for this.
Deeper investigation pointed out it occurs since angular version @angular/forms 7.2.2 and @angular/flex-layout": "^7.0.0-beta.23

**Comment by hamzahamidi** [comment]
Hi @woutervs . Thank you for using Angular6-json-schema-form. Can you please provide a valid JSON to reproduce this issue?

**Comment by woutervs** [comment]
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Contact": {
      "type": "object",
      "properties": {
        "Displayname": {
          "type": [
            "string"
          ]
        },
        "Id": {
          "type": "integer"
        }
      },
      "required": [
        "Displayname",
        "Id"
      ]
    }
  },
  "type": "object",
  "properties": {
    "Firstname": {
      "type": [
        "string",
        "null"
      ],
      "minLength": 2
    },
    "Lastname": {
      "type": "string"
    },
    "Email": {
      "type": [
        "string",
        "null"
      ],
      "format": "email"
    },
    "Birthday": {
      "type": "string",
      "format": "date"
    },
    "Contact": {
      "$ref": "#/definitions/Contact"
    }
  },
  "required": [
    "Firstname",
    "Lastname",
    "Email",
    "Birthday"
  ]
}

In a clean angular project with material design all at the latest version.

**Comment by hamzahamidi** [comment]
I tried to reproduce the issue with the following JSON, but I couldn't. Can you please explain further the steps using the DEMO?
```json

{
   "schema": {
      "type": "object",
      "title": "Comment",
      "properties": {
         "name": {
            "title": "Name",
            "type": "string"
         },
         "email": {
            "title": "Email",
            "type": "string",
            "pattern": "^S+@S+$",
            "description": "Email will be used for evil."
         },
         "comment": {
            "title": "Comment",
            "type": "string",
            "maxLength": 20,
            "validationMessage": "Don't be greedy!"
         },
         "contact": {
            "type": "object",
            "title": "Contact",
            "properties": {
               "firstname": {
                  "title": "Firstname",
                  "type": "string"
               },
               "lastname": {
                  "title": "Lastname",
                  "type": "string"
               }
            }
         }
      },
      "required": [
         "name",
         "email",
         "comment"
      ]
   }
}
```

**Comment by hamzahamidi** [comment]
Can you reproduce the issue in the demo? https://hamidihamza.com/Angular6-json-schema-form

**Comment by woutervs** [comment]
So what I did to reproduce it in the demo app
1.: Clean git pull of the master
2.: npm install
3.: Create test-schema.json src\assets\example-schemas\test-schema.json
4.: src\app\demo.module.ts fix imports
5.: src\app\demo.component.ts fix imports
6.: src\app\example-schemas.model.ts add test-schema
7.: ng s -o
If you look in developer tools you'll see the endswith error

**Comment by hamzahamidi** [comment]
Maybe related to https://github.com/angular/flex-layout/issues/1011

**Comment by woutervs** [comment]
Not only related, but the exact error.

**Comment by woutervs** [comment]
Reverting to 7.0.0-beta.19 seems to resolve the issue for now.
Thanks for pointing out the angular/flex-layout#1011 issue I hadn't found it earlier because I first added this issue in the angular7-json-schema-form fork of this project, though that developer doesn't seem to work on it anymore.

**Comment by hamzahamidi** [comment]
Closed as not related to Angular6-json-schema-form

**Comment by lamba92** [comment]
Reverting to 7.0.0-beta19 did not solve the issue for me. Have you done something else?

**Comment by syrine10** [comment]
Hello I have the same problem and I'm in angular 8. Did you solve this ?
