### ISSUE TITLE
All of lodash is imported

### ISSUE THREAD

**Issue by jpkolind** [hamzahamidi/Angular6-json-schema-form#75]
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [x] Bootstrap3FrameworkModule — Bootstrap 3
* [x] Bootstrap4FrameworkModule — Bootstrap 4
* [x] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  

This library depends on Lodash and imports _. into the components and services - which is not tree shakable by Webpack. It should instead import specific functions from the lodash-es (https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd) 

Would you accept a pull request to fix?

**Comment by hamzahamidi** [comment]
Yes of course. Thank you @jpkolind
