### ISSUE TITLE
Can`t import JsonSchemaFormModule

### ISSUE THREAD

**Issue by sverdlov** [hamzahamidi/Angular6-json-schema-form#88]
**Describe the bug**
which template:
* [ ] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [x] Other (please specify below)
  
Can`t import JsonSchemaFormModule

**To Reproduce**

1. npm i angular6-json-schema-form;
2. import JsonSchemaFormModule, NoFrameworkModule  from 'angular6-json-schema-form'; to component module, and add it to imports `imports: [ ... NoFrameworkModule, JsonSchemaFormModule.forRoot(NoFrameworkModule) ... ]` as described here [https://github.com/hamzahamidi/Angular6-json-schema-form/blob/master/src/app/demo.module.ts#L15](url)
3. add 
`<json-schema-form
  loadExternalAssets="true"
  [schema]="yourJsonSchema"
  framework="no-framework"
  (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>`
to template;
4. Got an error Module '"/node_modules/angular6-json-schema-form/angular6-json-schema-form"' has no exported member 'JsonSchemaFormModule'.

**Expected behavior**
It must worked

**Desktop (please complete the following information):**

- OS: [Linux Mint]
- Browser [chrome]
- Version [73]

**Log output covering before error and any error statements**

```logs
`Compiled with warnings.
ERROR in src/app/pages/control-panel/control-panel.module.ts(38,10): error TS2305: Module '"/home/sverdlov/WebstormProjects/frodo-reborn/node_modules/angular6-json-schema-form/angular6-json-schema-form"' has no exported member 'JsonSchemaFormModule'.
`
```

**Comment by hamzahamidi** [comment]
Hi @sverdlov . That's not how you import `angular6-json-schema-form`.
You need to follow the following steps as mentioned in the docs
**NB: note that you shouldn't import `JsonSchemaFormModule` :**
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { Bootstrap4FrameworkModule } from 'angular6-json-schema-form';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [ AppComponent ],
  imports: [
    BrowserModule
    Bootstrap4FrameworkModule
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```
And you use the component like the following:
```html
<json-schema-form
loadExternalAssets="true"
[schema]="schema"
framework="bootstrap-4"
(onSubmit)="submit($event)">
</json-schema-form>
```
If you still face the same issue, can you make a repository to reproduce this issue?

**Comment by sverdlov** [comment]
Hi. Thanks for the quick response. First of all, I did everything as mentioned in the docs, but get some error Module not found for @angular/flex-layout and lodash-es. After I installed them manually, all worked.
