### ISSUE TITLE
After using the new version 7.1.0 getting lodash errors

### ISSUE THREAD

**Issue by mayankkalbhor** [hamzahamidi/Angular6-json-schema-form#90]
After using the new version 7.1.0 getting lodash errors

**To Reproduce**

1. npm install angular6-json-schema-form
2. Add the code in app.module.ts
3. Do npm start 
4. Error: 
ERROR in ./node_modules/angular6-json-schema-form/fesm5/angular6-json-schema-form.js
Module not found: Error: Can't resolve 'lodash-es/cloneDeep' in 'C:\Users\mayank\node_modules\angular6-json-schema-form\fesm5'
ERROR in ./node_modules/angular6-json-schema-form/fesm5/angular6-json-schema-form.js
Module not found: Error: Can't resolve 'lodash-es/filter' in 'C:\Users\mayank\node_modules\angular6-json-schema-form\fesm5'
ERROR in ./node_modules/angular6-json-schema-form/fesm5/angular6-json-schema-form.js
Module not found: Error: Can't resolve 'lodash-es/isEqual' in 'C:\Users\mayank\node_modules\angular6-json-schema-form\fesm5'
ERROR in ./node_modules/angular6-json-schema-form/fesm5/angular6-json-schema-form.js
Module not found: Error: Can't resolve 'lodash-es/map' in 'C:\Users\mayank\node_modules\angular6-json-schema-form\fesm5'
ERROR in ./node_modules/angular6-json-schema-form/fesm5/angular6-json-schema-form.js
Module not found: Error: Can't resolve 'lodash-es/uniqueId' in 'C:\Users\mayank\node_modules\angular6-json-schema-form\fesm5'

**Comment by hamzahamidi** [comment]
Thank you for poiting out this issue. You need to install lodash-es

**Comment by mayankkalbhor** [comment]
@hamzahamidi Thanks
