### ISSUE TITLE
Option to generate `<mat-label>` is missing

### ISSUE THREAD

**Issue by redmagic** [hamzahamidi/Angular6-json-schema-form#91]
**Describe the bug**
which template:

* [x] MaterialDesignFrameworkModule — Material Design
* [ ] Bootstrap3FrameworkModule — Bootstrap 3
* [ ] Bootstrap4FrameworkModule — Bootstrap 4
* [ ] NoFrameworkModule — plain HTML
* [ ] Other (please specify below)
  
`<mat-label>` is not generated for form fields at https://github.com/hamzahamidi/Angular6-json-schema-form/blob/5ea51cfb8a0f33375ee39bceabc561cefa8ad569/projects/angular6-json-schema-form/src/lib/framework-library/material-design-framework/material-input.component.ts#L9-L56

**To Reproduce**
1. Add a form field without configuration, this creates a 'standard' form field.
2. Try to add a floating label to this field.

**Expected behavior**
Expect to have a configuration option to add a `<mat-label>` to the form field.

**Context**
It should be able to use floating labels in combination with the various field appearances as described here: https://material.angular.io/components/form-field/overview#form-field-appearance-variants

**Possible Implementation**
Expand the `material-input.component.ts` with an option to generate a `<mat-label>`

**Comment by wholypantalones** [comment]
I have a pull-request with mat-label, support for appearance variants and using MAT_FORM_FIELD_DEFAULT_OPTIONS and/or MAT_LABEL_GLOBAL_OPTIONS here: https://github.com/hamzahamidi/Angular6-json-schema-form/pull/103

**Comment by wholypantalones** [comment]
Pull request https://github.com/hamzahamidi/Angular6-json-schema-form/pull/103 has been merged.
