### ISSUE TITLE
schemaFormRedraw?

### ISSUE THREAD

**Issue by anasofiapaixao** [hamzahamidi/Angular6-json-schema-form#96]
Is there any way to force a redraw of the form? I need to update a select's `titleMap`, and can't see the changes reflected in the select's options. I used to be able to accomplish this with
`$scope.broadcast('schemaFormRedraw')`
in angular-schema-form.

**Comment by anasofiapaixao** [comment]
For anyone else who comes across this issue: after digging further in the code, I discovered you can do a redraw with `JsonSchemaFormComponent.initializeForm()`.

Declare the form in your component's html with
```
<json-schema-form #yourFormIdentifier>
   .... 
</json-schema-form>
```

and use @ViewChild to have access to the component's instance:
```
  @ViewChild("yourFormIdentifier") yourFormInstance: JsonSchemaFormComponent;
```

With this, you can call `yourFormInstance.initializeForm()` to perform a redraw.

**Comment by dbuddha** [comment]
Hello @anasofiapaixao ,
Check your object instances, you can two way bind the titleMap array/object if you dont loose your pointer / instance.

Regards,
Diogo

**Comment by dbuddha** [comment]
@anasofiapaixao try this:

On the component you have your form object set a property in the constructor like this `this.timeStamp = new Date().getTime();`
In different occasions you write and read from the form object print the timeStamp number.
If they are all the same then you have a sigleton object.

Hope this is helpfull.

Regards

**Comment by anasofiapaixao** [comment]
Thank you, if it works it could simplify the code quite a bit! It didn't even cross my mind because I remember this not working in `angular-schema-form`, and I didn't stop to consider it might work here when I did the Angular port.
